In [16]:
import pandas as pd
import numpy as np
from PIL import Image
import urllib.request
import io
import requests
import validators

In [17]:
works_raw = pd.read_csv('data/collection/artwork_data.csv')
works_raw

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3166: DtypeWarning: Columns (9,13) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â€“7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975,2013.0,object: 305 x 305 x 135 mm,305,305.0,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976,2013.0,object: 305 x 305 x 135 mm,305,305.0,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410.0,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000,2013.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...
69200,127035,T13869,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764â€“96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764,2013.0,unconfirmed: 508 x 660 mm,508,660.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [25]:
works_raw.artist.value_counts()

Turner, Joseph Mallord William    39389
Jones, George                      1046
Moore, Henry, OM, CH                623
Daniell, William                    612
Beuys, Joseph                       578
                                  ...
Davis, Ron                            1
Herbert, J.G.S.                       1
Stanley, Lady Dorothy                 1
Vlahos, Vangelis                      1
Swain, Tony                           1
Name: artist, Length: 3336, dtype: int64

In [52]:
works_raw['ByJMWT'] = works_raw['artist'] == 'Turner, Joseph Mallord William'

JMWT = works_raw['ByJMWT'] == True
Other_artists = works_raw['ByJMWT'] == False

JMWT_works = works_raw[JMWT]
JMWT_works_local = JMWT_works.sample(n = 45)

Other_artists_works = works_raw[Other_artists]
Other_artist_works_local = Other_artists_works.sample(n = 45)

In [48]:
len(JMWT_works)

39389

In [49]:
len(Other_artists_works)

29812

In [19]:
artists_raw = pd.read_csv('data/collection/artist_data.csv')
artists_raw

,id,name,gender,dates,yearOfBirth,yearOfDeath,placeOfBirth,placeOfDeath,url
0,10093,"Abakanowicz, Magdalena",Female,born 1930,1930.0,NaN,Polska,NaN,http://www.tate.org.uk/art/artists/magdalena-a...
1,0,"Abbey, Edwin Austin",Male,1852â€“1911,1852.0,1911.0,"Philadelphia, United States","London, United Kingdom",http://www.tate.org.uk/art/artists/edwin-austi...
2,2756,"Abbott, Berenice",Female,1898â€“1991,1898.0,1991.0,"Springfield, United States","Monson, United States",http://www.tate.org.uk/art/artists/berenice-ab...
3,1,"Abbott, Lemuel Francis",Male,1760â€“1803,1760.0,1803.0,"Leicestershire, United Kingdom","London, United Kingdom",http://www.tate.org.uk/art/artists/lemuel-fran...
4,622,"Abrahams, Ivor",Male,born 1935,1935.0,NaN,"Wigan, United Kingdom",NaN,http://www.tate.org.uk/art/artists/ivor-abraha...
...,...,...,...,...,...,...,...,...,...
3527,12542,"Zorio, Gilberto",Male,born 1944,1944.0,NaN,"Andorno Micca, Italia",NaN,http://www.tate.org.uk/art/artists/gilberto-zo...
3528,2186,"Zox, Larry",Male,born 1936,1936.0,NaN,"Des Moines, United States",NaN,http://www.tate.org.uk/art/artists/larry-zox-2186
3529,621,"Zuccarelli, Francesco",Male,1702â€“1788,1702.0,1788.0,Italia,Firenze,http://www.tate.org.uk/art/artists/francesco-z...
3530,2187,"Zuloaga, Ignacio",Male,1870â€“1945,1870.0,1945.0,EspaÃ±a,EspaÃ±a,http://www.tate.org.uk/art/artists/ignacio-zul...
3531,2188,"Zyw, Aleksander",Male,1905â€“1995,1905.0,1995.0,Polska,NaN,http://www.tate.org.uk/art/artists/aleksander-...

In [41]:
name_gender = artists_raw.iloc[:,[1,2]]
works_with_gender = works_raw.merge(name_gender, how = 'left', left_on = 'artist', right_on = 'name')
works_with_gender.gender.value_counts()

Male      65892
Female     2727
Name: gender, dtype: int64

In [53]:
male_bool = works_with_gender.gender == 'Male'
female_bool = works_with_gender.gender == 'Female' 

F_set = works_with_gender[female_bool]
F_set_local = F_set.sample(n = 45)

M_set = works_with_gender[male_bool]
M_set_local = M_set.sample(n = 45)

In [ ]:
def mk_im_dir (dataframe):